# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZTProgressHUD' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZTProgressHUD

  target 'ZTProgressHUDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZTProgressHUDUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
